local function run(msg, matches)
    if is_owner(msg) then
        return
    end
    local data = load_data(_config.moderation.data)
    if data[tostring(msg.to.id)] then
        if data[tostring(msg.to.id)]['settings'] then
            if data[tostring(msg.to.id)]['settings']['antifosh'] then
                lock_fosh = data[tostring(msg.to.id)]['settings']['antifosh']
            end
        end
    end
    local chat = get_receiver(msg)
    local user = "user#id"..msg.from.id
    if lock_fosh == "yes" then
        send_large_msg(chat, 'بدلیل فحاشی به اعضای گروه شما به مدتی حذف شدید')
        chat_del_user(chat, user, ok_cb, true)
    end
end
 
return {
  patterns = {
    "[Kk][Ii][Rr]",
    "[Kk][Oo][Ss]",
    "[Nn][Aa][Nn][Aa][Tt]",
    "کس(.*)",
    "کون(.*)",
    "کیر(.*)",
    "ممه(.*)",
    "سکس(.*)",
    "سیکتیر(.*)",
    "قهبه(.*)",
    "بسیک(.*)",
    "بیناموس(.*)",
    "اوبی(.*)",
    "کونی(.*)",
    "بیشرف(.*)",
    "کس ننه(.*)",
    "ساک(.*)",
    "کیری(.*)",
    "خار کوسه(.*)",
    "ننه(.*)",
    "خواهرتو(.*)",
    "سکسی(.*)",
    "کسکش(.*)",
    "سیک تیر(.*)",
    "گاییدم(.*)",
    "میگام(.*)",
    "میگامت(.*)",
    "بسیک(.*)",
    "خواهرت(.*)",
    "خارتو(.*)",
    "کونت(.*)",
    "کوست(.*)",
    "شورت(.*)",
    "سگ(.*)",
    "کیری(.*)",
    "دزد(.*)",
    "ننت(.*)",
    "ابمو(.*)",
    "حرومی(.*)",
    "بخورش(.*)",
    "بلیسش(.*)",
    "کیرم(.*)",
    "بگیرش(.*)",
    "کسده(.*)",
    "کوس(.*)",
    "ننه سگ(.*)",
    "کیر دزد(.*)",
    "تخمم(.*)",
    "رو مخم(.*)",
    "رو کیرم(.*)",
    "کیر خوار(.*)",
    "سیک اوت(.*)",
    "دعوا(.*)",
    "مادرتو(.*)",
    "خواهرت(.*)",
    "نون خوره سره(.*)",
    "کیر سر دره(.*)",
    "کیرم سر دره(.*)",
    "بکنمت(.*)",
    "میکنمت(.*)",
    "جنده(.*)",
    "زنتو(.*)",
    "زنتو گاییدم(.*)",
    "سگ گاییدت(.*)",
    "عمتو(.*)",
    "عمت گاییدم(.*)",
    "عمتو سگ (.*)",
    "مادرت با گراز(.*)",
    "حشرم(.*)",
    "حشری(.*)",
    "کونکش(.*)",
    "گه(.*)",
    "گهخور(.*)",
    "گه نخور(.*)",
    "گهنخور(.*)",
    "آب کیرکو(.*)",
    "اب کیرم(.*)",
    "ریدم دهنت(.*)",
    "گاییدمتون(.*)",
    "اسپم کنم(.*)",
    "اسپم کن(.*)",
    "اسپم بده(.*)",
    "ریدم تو گروه(.*)",
    "کیرمم نیستین(.*)",
    "حرومزاده(.*)",
    "پفیوس(.*)",
    "پفیوز(.*)",
    "دیوس(.*)",
    "جاکش(.*)",
    "kir(.*)",
    "kos(.*)",
    "kon(.*)",
    "kun(.*)",
    "mame(.*)",
    "koloft(.*)",
    "bokhoresh(.*)",
    "haromi(.*)",
    "kuni khan(.*)",
    "kose nanat(.*)",
    "kose mamanet(.*)",
    "kose bibit(.*)",
    "nagaedam(.*)",
    "man gaedam(.*)",
    "kon taqara(.*)",
    "spamer(.*)",
    "robot spamer(.*)",
    "sapam konam(.*)",
    "b ga(.*)",
    "b ga midamesh(.*)",
    "fuck(.*)",
    "dava(.*)",
    "bokonetam(.*)",
    "bokone nanatam(.*)",
    "bokone madaretam(.*)",
    "sag pedar(.*)",
    "babato gaedam(.*)",
    "mame 85(.*)",
    "kardameshon(.*)",
    "gaedameton(.*)",
    "migameshon(.*)",
    "goh(.*)",
    "goh bokhor(.*)",
    "goh nakhor(.*)",
    "kose khare admin inja(.*)",
    "kose madare admin inja(.*)",
    "zane admino(.*)",
    "zane admino gaedam(.*)",
    "madare admin gaedam(.*)",
    "madare sudo gaedam(.*)",
    "kahahre sudo gaedam(.*)",
    "kune admino gaedam(.*)",
    "nagaedam(.*)",
    "belisesh(.*)",
    "kharkose(.*)",
    "madar qahve(.*)",
    "bokonamet(.*)",
    "hamyaro gaedam(.*)",
    "group gaedam(.*)",
    "mankey(.*)",
    "kiram dahane admiensh(.*)",
    "kiram dahane sudo(.*)",
    "kiram dahane sudosh(.*)",
    "siktir(.*)",
    "suck me(.*)",
    "sak bezan(.*)",
    "saresho belis(.*)",
    "golshifte(.*)",
    "asare manfi pishro(.*)",
    "kondegari dar nakun(.*)",
    "bokonetonam(.*)",
    "omadam spam(.*)",
    "omadam spam bedam(.*)",
    "ovordam spamero(.*)",
    "begayim hamyaro(.*)",
    "off kunim hamyaro(.*)",
    "sick(.*)",
    "sick out(.*)",
    "fuck you mather(.*)",
    "fuck you(.*)",
    "xnxx.com(.*)",
    "xvideos.com(.*)",
    "xxx(.*)",
    "porn(.*)",
    "sex(.*)",
    "sexy(.*)",
    "shahvani(.*)",
    "shahvatam(.*)",
    "daus(.*)",
    "pufyos(.*)",
    "pufiyoz(.*)",
    "pofiyoz(.*)",
    "sicktir(.*)",
    "porner(.*)",
    "alexsiz(.*)",
    "alexsis(.*)",
    "janisinz(.*)",
    "junisynz(.*)",
    "junisyns(.*)",
    "alleta(.*)",
    "aleta(.*)",
    "oshen(.*)",
    "abam omad(.*)",
    "riki(.*)",
    "haromzade(.*)",
    "kardam(.*)",
    "mikonam(.*)",
    "mikonamesh(.*)",
    "face tokhmi(.*)",
    "kir to ax profilet(.*)",
    "harfie(.*)",
    "جق(.*)"
  },
  run = run
}
--Copyright and edit; @Mhmafi
--Persian Translate; @Mhmafi
--ch : @Hamyargroupp
--همیار گروه--
